/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package budgetbuddy;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author being
 */
public class homeGUI extends javax.swing.JFrame {

    /**
     * Creates new form homeGUI
     */
    public homeGUI() {
        
        initComponents();
        displayTable();
        getEntries();
        
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png")));
        Home.setBorderPainted(true);
        Home.setContentAreaFilled(false);

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png")));
        refresh.setBorderPainted(false);
        refresh.setContentAreaFilled(false);

        Category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png")));
        Category.setBorderPainted(false);
        Category.setContentAreaFilled(false);
    }
    
    private void displayTable(){
//        javax.swing.table.DefaultTableModel table = (javax.swing.table.DefaultTableModel) homeTable.getModel();
        try{
            homeCategory.removeAllItems();
            ResultSet rs = dbConnect.state.executeQuery("select * from category");
            while(rs.next()){
                homeCategory.addItem(rs.getString("category"));
            }
        }catch(HeadlessException | SQLException ex){ //Exception handaler
            JOptionPane.showMessageDialog(null,ex);
        }
    }

    private void getEntries(){
        javax.swing.table.DefaultTableModel table = (javax.swing.table.DefaultTableModel) homeTable.getModel();
        try{
            int rowCount = table.getRowCount();
            while (rowCount-- != 0) {
                table.removeRow(0);
            }
            ResultSet rs = dbConnect.state.executeQuery("SELECT * FROM `spending`");
            
            int total = 0;
            while (rs.next()) {
                int id = rs.getInt("id");
                Float amt = rs.getFloat("amount");
                String category = rs.getString("category");
                Date date = rs.getDate("spending_date");
                Object obj[] = {id, date, amt, category};
                table.addRow(obj);
                
                total+=amt;
                totalNumber.setText(total+"");
            }
        }catch(HeadlessException | SQLException ex){ //Exception handaler
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeDate = new com.toedter.calendar.JDateChooser();
        navPanel = new java.awt.Panel();
        Home = new javax.swing.JButton();
        Category = new javax.swing.JButton();
        homeDateLabel = new javax.swing.JLabel();
        homeAmount = new javax.swing.JTextField();
        homeAmountLabel = new javax.swing.JLabel();
        homeAmountLabel1 = new javax.swing.JLabel();
        homeCategory = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        totalSpendingLabel = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        homeTable = new javax.swing.JTable();
        spendingLabel = new javax.swing.JLabel();
        totalNumber = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(255, 255, 255));

        navPanel.setBackground(new java.awt.Color(102, 102, 102));

        Home.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        Home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        Category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryMouseClicked(evt);
            }
        });
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(Category, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(144, 144, 144)
                .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(143, 143, 143))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(Category, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        homeDateLabel.setText("Date:");

        homeAmountLabel.setText("Category:");

        homeAmountLabel1.setText("Amount:");

        homeCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeCategoryActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        totalSpendingLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalSpendingLabel.setText("Total Spending:");

        homeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Amount", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        homeTable.getTableHeader().setReorderingAllowed(false);
        ScrollPane.setViewportView(homeTable);

        spendingLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        spendingLabel.setText("This month spending:");

        totalNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalNumber.setText("0");

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalSpendingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spendingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(homeDateLabel)
                                    .addComponent(homeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(homeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(homeAmountLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(homeAmountLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addComponent(submit))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(homeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton2)))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeDateLabel)
                    .addComponent(homeAmountLabel1)
                    .addComponent(homeAmountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(refresh, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(homeDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(spendingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalSpendingLabel)
                    .addComponent(totalNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {homeAmount, homeCategory, homeDate});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
       
    }//GEN-LAST:event_HomeActionPerformed

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        
    }//GEN-LAST:event_CategoryActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        new homeGUI().setVisible(true);
    }//GEN-LAST:event_HomeMouseClicked

    private void CategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryMouseClicked
        new categoryGUI().setVisible(true);
        new homeGUI().setVisible(false);
    }//GEN-LAST:event_CategoryMouseClicked

    private void homeCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeCategoryActionPerformed
    
    }//GEN-LAST:event_homeCategoryActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        displayTable();
    }//GEN-LAST:event_refreshActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row_index = homeTable.getSelectedRow();

        if (row_index != -1) {
            try {
                int id = (int) homeTable.getValueAt(row_index, 0);
                dbConnect.state.executeUpdate("DELETE FROM `spending` WHERE id = " + id + "");

                getEntries();
            } catch (HeadlessException | NumberFormatException | SQLException ex) { //Exception handaler
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try{
            java.util.Date d = homeDate.getDate();
            String samount = homeAmount.getText();
            String category = (String)homeCategory.getSelectedItem();
            
            int amount = Integer.parseInt(samount);
            java.sql.Date date = new java.sql.Date(d.getTime());
            
            if(d != null && !samount.equals("") && !category.equals("")){
                dbConnect.state.executeUpdate("insert into spending (category,spending_date,amount) value('"+category+"','"+date+"',"+amount+")");
            }else{
                JOptionPane.showMessageDialog(null,"Please fill all details !!!");
            }
            getEntries();
        }catch(HeadlessException | NumberFormatException | SQLException ex){ //Exception handaler
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new homeGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Category;
    private javax.swing.JButton Home;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTextField homeAmount;
    private javax.swing.JLabel homeAmountLabel;
    private javax.swing.JLabel homeAmountLabel1;
    private javax.swing.JComboBox<String> homeCategory;
    private com.toedter.calendar.JDateChooser homeDate;
    private javax.swing.JLabel homeDateLabel;
    private javax.swing.JTable homeTable;
    private javax.swing.JButton jButton2;
    private java.awt.Panel navPanel;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel spendingLabel;
    private javax.swing.JButton submit;
    private javax.swing.JLabel totalNumber;
    private javax.swing.JLabel totalSpendingLabel;
    // End of variables declaration//GEN-END:variables
}
